void plot_NrecNgenCosTheta_IDR() 
{
  TString topDirPath(gSystem->GetFromPipe("echo $MPDIR")); // MPDIR should be defined in an init script.
  TString styleMacroPath(topDirPath+"/macros/ildstyle.C");
  gROOT->LoadMacro(styleMacroPath.Data());

  TString filePath_l5(topDirPath+"run_l5/plots/plots.root");
  TString filePath_s5(topDirPath+"run_s5/plots/plots.root");
  TFile* finl5 = new TFile(filePath_l5.Data());
  TFile* fins5 = new TFile(filePath_s5.Data());
  TNtuple* SignalPhoton_nungLR = static_cast<TNtuple*>(finl5->Get("SignalPhoton_nungLR"));
  //TNtuple* SignalPhoton_nungRL = static_cast<TNtuple*>(finl5->Get("SignalPhoton_nungRL"));
  TNtuple* SignalPhoton_nungLR_s5 = static_cast<TNtuple*>(fins5->Get("SignalPhoton_nungLR"));
  //TNtuple* SignalPhoton_nungRL = static_cast<TNtuple*>(finl5->Get("SignalPhoton_nungRL"));

  SignalPhoton_nungLR->Draw("nrec_pfoAsPhoton+nrec_pfoAsNonPhoton:TMath::Cos(gen_theta)>>hSuml5(50,0,1,6,-0.5,5.5)","nAcceptablePhoton_MC_per_evt==1&&gen_e>2&&fabs(gen_theta)>7*TMath::Pi()/180.&&fabs(gen_theta)<173*TMath::Pi()/180.&&nISR==1&&gen_ndaughters<2");
  SignalPhoton_nungLR_s5->Draw("nrec_pfoAsPhoton+nrec_pfoAsNonPhoton:TMath::Cos(gen_theta)>>hSums5(50,0,1,6,-0.5,5.5)","nAcceptablePhoton_MC_per_evt==1&&gen_e>2&&fabs(gen_theta)>7*TMath::Pi()/180.&&fabs(gen_theta)<173*TMath::Pi()/180.&&nISR==1&&gen_ndaughters<2");
  SignalPhoton_nungLR->Draw("nrec_pfoAsPhoton:TMath::Cos(gen_theta)>>hPl5(50,0,1,6,-0.5,5.5)","nAcceptablePhoton_MC_per_evt==1&&gen_e>2&&fabs(gen_theta)>7*TMath::Pi()/180.&&fabs(gen_theta)<173*TMath::Pi()/180.&&nISR==1&&gen_ndaughters<2");
  SignalPhoton_nungLR_s5->Draw("nrec_pfoAsPhoton:TMath::Cos(gen_theta)>>hPs5(50,0,1,6,-0.5,5.5)","nAcceptablePhoton_MC_per_evt==1&&gen_e>2&&fabs(gen_theta)>7*TMath::Pi()/180.&&fabs(gen_theta)<173*TMath::Pi()/180.&&nISR==1&&gen_ndaughters<2");
  SignalPhoton_nungLR->Draw("nrec_pfoAsNonPhoton:TMath::Cos(gen_theta)>>hNPl5(50,0,1,6,-0.5,5.5)","nAcceptablePhoton_MC_per_evt==1&&gen_e>2&&fabs(gen_theta)>7*TMath::Pi()/180.&&fabs(gen_theta)<173*TMath::Pi()/180.&&nISR==1&&gen_ndaughters<2");
  SignalPhoton_nungLR_s5->Draw("nrec_pfoAsNonPhoton:TMath::Cos(gen_theta)>>hNPs5(50,0,1,6,-0.5,5.5)","nAcceptablePhoton_MC_per_evt==1&&gen_e>2&&fabs(gen_theta)>7*TMath::Pi()/180.&&fabs(gen_theta)<173*TMath::Pi()/180.&&nISR==1&&gen_ndaughters<2");

  TH2D* hSuml5 = static_cast<TH2D*>(gROOT->FindObject("hSuml5"));
  TH2D* hSums5 = static_cast<TH2D*>(gROOT->FindObject("hSums5"));
  TH2D* hPl5 = static_cast<TH2D*>(gROOT->FindObject("hPl5"));
  TH2D* hPs5 = static_cast<TH2D*>(gROOT->FindObject("hPs5"));
  TH2D* hNPl5 = static_cast<TH2D*>(gROOT->FindObject("hNPl5"));
  TH2D* hNPs5 = static_cast<TH2D*>(gROOT->FindObject("hNPs5"));

  TGraphErrors* gSuml5 = new TGraphErrors();
  TGraphErrors* gSums5 = new TGraphErrors();
  TGraphErrors* gPl5 = new TGraphErrors();
  TGraphErrors* gPs5 = new TGraphErrors();
  TGraphErrors* gNPl5 = new TGraphErrors();
  TGraphErrors* gNPs5 = new TGraphErrors();
  int nxbins = 50;

  for (int ix = 0; ix < nxbins; ix++) {
    stringstream hname_l5, hname_s5;
    stringstream hname_Pl5, hname_Ps5;
    stringstream hname_NPl5, hname_NPs5;
    hname_l5 << "bsuml5" << ix << ends;
    hname_s5 << "bsums5" << ix << ends;
    hname_Pl5 << "bPl5" << ix << ends;
    hname_Ps5 << "bPs5" << ix << ends;
    hname_NPl5 << "bNPl5" << ix << ends;
    hname_NPs5 << "bNPs5" << ix << ends;
    hSuml5->ProjectionY(hname_l5.str().data(),ix,ix+1);
    hSums5->ProjectionY(hname_s5.str().data(),ix,ix+1);
    hPl5->ProjectionY(hname_Pl5.str().data(),ix,ix+1);
    hPs5->ProjectionY(hname_Ps5.str().data(),ix,ix+1);
    hNPl5->ProjectionY(hname_NPl5.str().data(),ix,ix+1);
    hNPs5->ProjectionY(hname_NPs5.str().data(),ix,ix+1);
    TH1D* hpSuml5 = static_cast<TH1D*>(gROOT->FindObject(hname_l5.str().data()));
    TH1D* hpSums5 = static_cast<TH1D*>(gROOT->FindObject(hname_s5.str().data()));
    TH1D* hpPl5 = static_cast<TH1D*>(gROOT->FindObject(hname_Pl5.str().data()));
    TH1D* hpPs5 = static_cast<TH1D*>(gROOT->FindObject(hname_Ps5.str().data()));
    TH1D* hpNPl5 = static_cast<TH1D*>(gROOT->FindObject(hname_NPl5.str().data()));
    TH1D* hpNPs5 = static_cast<TH1D*>(gROOT->FindObject(hname_NPs5.str().data()));
    gSuml5->SetPoint(ix,(ix+0.5)/nxbins,hpSuml5->GetMean());
    gSuml5->SetPointError(ix,1./nxbins/TMath::Sqrt(12),hpSuml5->GetRMS()/TMath::Sqrt(hpSuml5->GetEntries()));
    gSums5->SetPoint(ix,(ix+0.5)/nxbins,hpSums5->GetMean());
    gSums5->SetPointError(ix,1./nxbins/TMath::Sqrt(12),hpSums5->GetRMS()/TMath::Sqrt(hpSums5->GetEntries()));
    gPl5->SetPoint(ix,(ix+0.5)/nxbins,hpPl5->GetMean());
    gPl5->SetPointError(ix,1./nxbins/TMath::Sqrt(12),hpPl5->GetRMS()/TMath::Sqrt(hpPl5->GetEntries()));
    gPs5->SetPoint(ix,(ix+0.5)/nxbins,hpPs5->GetMean());
    gPs5->SetPointError(ix,1./nxbins/TMath::Sqrt(12),hpPs5->GetRMS()/TMath::Sqrt(hpPs5->GetEntries()));
    gNPl5->SetPoint(ix,(ix+0.5)/nxbins,hpNPl5->GetMean());
    gNPl5->SetPointError(ix,1./nxbins/TMath::Sqrt(12),hpNPl5->GetRMS()/TMath::Sqrt(hpNPl5->GetEntries()));
    gNPs5->SetPoint(ix,(ix+0.5)/nxbins,hpNPs5->GetMean());
    gNPs5->SetPointError(ix,1./nxbins/TMath::Sqrt(12),hpNPs5->GetRMS()/TMath::Sqrt(hpNPs5->GetEntries()));
  }

  TLatex *tex = new TLatex();
  tex->SetTextSize(0.05);
  TLatex *texboundary = new TLatex();
  texboundary->SetTextSize(0.02);
  texboundary->SetTextAngle(90);

  TLine *gaplinel5 = new TLine(0.793095,0.98,0.793095,1.03);
  gaplinel5->SetLineColor(kBlue);
  gaplinel5->SetLineStyle(3);
  TLine *gaplines5 = new TLine(0.849125,0.98,0.849125,1.03);
  gaplines5->SetLineColor(kRed);
  gaplines5->SetLineStyle(3);

  TH1D* axis = new TH1D("axis",";cos#theta_{MC};#bar{N_{rec}/N_{gen}}",1,0.,1.);
  TCanvas* csum = new TCanvas("csum","",600,600);
  gSuml5->SetName("gSuml5");
  gSums5->SetName("gSums5");
  //gSuml5->SetTitle(";cos#theta_{MC};#bar{N_{rec}/N_{gen}}");
  //gSuml5->GetXaxis()->SetRangeUser(0.,1.);
  //gSuml5->GetYaxis()->SetRangeUser(0.98,1.03);
  axis->GetYaxis()->SetTitleOffset(1.4);
  axis->GetYaxis()->SetRangeUser(0.98,1.03);
  gSums5->SetMarkerStyle(kOpenCircle);
  gSuml5->SetMarkerColor(kBlue);
  gSums5->SetMarkerColor(kRed);
  gSuml5->SetLineColor(kBlue);
  gSums5->SetLineColor(kRed);
  axis->Draw();
  gaplinel5->Draw();
  gaplines5->Draw();
  gSuml5->Draw("pe same");
  gSums5->Draw("pe same");
  TLegend *leg = new TLegend(0.25,0.77,0.4,0.67);
  leg->SetTextFont(62);
  leg->SetTextSize(0.03); 
  leg->SetTextAlign(12);
  leg->AddEntry(gSuml5,"IDR-L","elp"); 
  leg->AddEntry(gSums5,"IDR-S","elp"); 
  leg->Draw();
  tex->DrawLatexNDC(0.25,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
  texboundary->DrawLatexNDC(0.76,0.2,"#color[4]{IDR-L Barrel-Endcap boundary}");
  texboundary->DrawLatexNDC(0.84,0.2,"#color[2]{IDR-S Barrel-Endcap boundary}");
  //tex->DrawLatexNDC(0.4,0.7,"#scale[0.5]{#font[42]{All PFOs}}");
  //TPaveText* pt = new TPaveText(0.55,0.855,0.895,0.895,"NDC");
  //pt->AddText("All PFOs");
  //pt->SetTextFont(42);
  //pt->SetTextSize(0.02);
  //pt->Draw();
  csum->RedrawAxis();
  csum->SetLeftMargin(0.2);
  csum->Print("NrecNgenCosTheta_allpfo_IDR.pdf");
  csum->Print("NrecNgenCosTheta_allpfo_IDR.C");

  TCanvas* cP = new TCanvas("cP","",600,600);
  gPl5->SetName("gPl5");
  gPs5->SetName("gPs5");
  //gPl5->SetTitle(";cos#theta_{MC};#bar{N_{rec}/N_{gen}}");
  //gPl5->GetYaxis()->SetRangeUser(0.98,1.03);
  //gPl5->GetXaxis()->SetRangeUser(0.,1.);
  gPs5->SetMarkerStyle(kOpenCircle);
  gPl5->SetMarkerColor(kBlue);
  gPs5->SetMarkerColor(kRed);
  gPl5->SetLineColor(kBlue);
  gPs5->SetLineColor(kRed);
  axis->Draw();
  gaplinel5->Draw();
  gaplines5->Draw();
  gPl5->Draw("pe same");
  gPs5->Draw("pe same");
  TLegend *leg2 = new TLegend(0.25,0.77,0.5,0.67);
  leg2->SetTextFont(62);
  leg2->SetTextSize(0.03); 
  leg2->SetTextAlign(12);
  leg2->AddEntry(gPl5,"IDR-L","elp"); 
  leg2->AddEntry(gPs5,"IDR-S","elp"); 
  leg2->Draw();
  tex->DrawLatexNDC(0.25,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
  texboundary->DrawLatexNDC(0.76,0.6,"#color[4]{IDR-L Barrel-Endcap boundary}");
  texboundary->DrawLatexNDC(0.84,0.6,"#color[2]{IDR-S Barrel-Endcap boundary}");
  //tex->DrawLatexNDC(0.4,0.7,"#scale[0.5]{#font[42]{PFOs reconstructed as photons}}");
  //TPaveText* pt2 = new TPaveText(0.4,0.75,0.8,0.7,"NDC");
  //TPaveText* pt2 = new TPaveText(0.55,0.855,0.895,0.895,"NDC");
  //pt2->AddText("PFOs reconstructed as photons");
  //pt2->SetTextFont(42);
  //pt2->SetTextSize(0.02);
  //pt2->Draw();
  cP->RedrawAxis();
  cP->SetLeftMargin(0.2);
  cP->Print("NrecNgenCosTheta_photon_IDR.pdf");
  cP->Print("NrecNgenCosTheta_photon_IDR.C");

  TCanvas* cNP = new TCanvas("cNP","",600,600);
  gNPl5->SetName("gNPl5");
  gNPs5->SetName("gNPs5");
  //gNPl5->SetTitle(";cos#theta_{MC};");
  //gNPl5->GetYaxis()->SetRangeUser(0.,0.05);
  axis->GetYaxis()->SetRangeUser(0.,0.05);
  gNPl5->GetXaxis()->SetRangeUser(0.,1.);
  gNPs5->SetMarkerStyle(kOpenCircle);
  gNPl5->SetMarkerColor(kBlue);
  gNPs5->SetMarkerColor(kRed);
  gNPl5->SetLineColor(kBlue);
  gNPs5->SetLineColor(kRed);
  axis->Draw();
  gaplinel5->Draw();
  gaplines5->Draw();
  gNPl5->Draw("pe same");
  gNPs5->Draw("pe same");
  TLegend *leg3 = new TLegend(0.25,0.77,0.5,0.67);
  leg3->SetTextFont(62);
  leg3->SetTextSize(0.03); 
  leg3->SetTextAlign(12);
  leg3->AddEntry(gNPl5,"IDR-L","elp"); 
  leg3->AddEntry(gNPs5,"IDR-S","elp"); 
  leg3->Draw();
  tex->Draw();
  tex->DrawLatexNDC(0.25,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
  texboundary->DrawLatexNDC(0.76,0.6,"#color[4]{IDR-L Barrel-Endcap boundary}");
  texboundary->DrawLatexNDC(0.84,0.6,"#color[2]{IDR-S Barrel-Endcap boundary}");
  //tex->DrawLatexNDC(0.4,0.7,"#scale[0.5]{#font[42]{PFOs reconstructed as non-photons}}");
  //TPaveText* pt3 = new TPaveText(0.55,0.855,0.895,0.895,"NDC");
  //pt3->AddText("PFOs reconstructed as non-photons");
  //pt3->SetTextFont(42);
  //pt3->SetTextSize(0.02);
  //pt3->Draw();
  cNP->SetLeftMargin(0.2);
  cNP->RedrawAxis();
  cNP->Print("NrecNgenCosTheta_nonphoton_IDR.pdf");
  cNP->Print("NrecNgenCosTheta_nonphoton_IDR.C");
}
