void drawPlots() {

  TString topDirPath(gSystem->GetFromPipe("echo $MPDIR")); // MPDIR should be defined in an init script.
  TString styleMacroPath(topDirPath+"/macros/ildstyle.C");
  TString rootFilePath(topDirPath+"/run_s5/plots/plots.root");
  gROOT->LoadMacro(styleMacroPath.Data());
  TFile* fin = new TFile(rootFilePath.Data());

  TH1F* hE_photon_nung                = static_cast<TH1F*>(fin->Get("hE_photon_nung"));
  TH1F* hNrecNgen_photon_nung         = static_cast<TH1F*>(fin->Get("hNrecNgen_photon_nung"));
  TGraphErrors* gNrecNgenEmc_photon_nung      = static_cast<TGraphErrors*>(fin->Get("gNrecNgenEmc_photon_nung")); 
  TGraphErrors* gNrecNgenCostheta_photon_nung = static_cast<TGraphErrors*>(fin->Get("gNrecNgenCostheta_photon_nung"));
  TH1F* hPt_ep_nung_other             = static_cast<TH1F*>(fin->Get("hPt_ep_nung_other"));
  TH1F* hPt_ep_nung_ol                = static_cast<TH1F*>(fin->Get("hPt_ep_nung_ol"));
  TH1F* hPt_ep_nung_isr               = static_cast<TH1F*>(fin->Get("hPt_ep_nung_isr"));
  TH1F* hPt_pfo_nung_isr              = static_cast<TH1F*>(fin->Get("hPt_pfo_nung_isr"));
  TH1F* hPt_pfo_nung_ol               = static_cast<TH1F*>(fin->Get("hPt_pfo_nung_ol"));
  TH1F* hPt_pfo_nung_other            = static_cast<TH1F*>(fin->Get("hPt_pfo_nung_other"));
  TH1F* hE_photon_nung_rest           = static_cast<TH1F*>(fin->Get("hE_photon_nung_rest"));
  TH1F* hE_photon_nung_ol             = static_cast<TH1F*>(fin->Get("hE_photon_nung_ol"));
  TH1F* hE_V0_nung_rest               = static_cast<TH1F*>(fin->Get("hE_V0_nung_rest"));
  TH1F* hE_V0_nung_ol                 = static_cast<TH1F*>(fin->Get("hE_V0_nung_ol"));
  TH1F* hE_neutron_nung_rest          = static_cast<TH1F*>(fin->Get("hE_neutron_nung_rest"));
  TH1F* hE_neutron_nung_ol            = static_cast<TH1F*>(fin->Get("hE_neutron_nung_ol"));
  TH1F* hE_electron_nung_rest         = static_cast<TH1F*>(fin->Get("hE_electron_nung_rest"));
  TH1F* hE_electron_nung_ol           = static_cast<TH1F*>(fin->Get("hE_electron_nung_ol"));
  TH1F* hE_muon_nung_rest             = static_cast<TH1F*>(fin->Get("hE_muon_nung_rest"));
  TH1F* hE_muon_nung_ol               = static_cast<TH1F*>(fin->Get("hE_muon_nung_ol"));
  TH1F* hE_pion_nung_rest             = static_cast<TH1F*>(fin->Get("hE_pion_nung_rest"));
  TH1F* hE_pion_nung_ol               = static_cast<TH1F*>(fin->Get("hE_pion_nung_ol"));
  TH1F* hEvis_pfo_nung                = static_cast<TH1F*>(fin->Get("hEvis_pfo_nung"));
  TH1F* hEvis_pfo_wo_pi_n_nung        = static_cast<TH1F*>(fin->Get("hEvis_pfo_wo_pi_n_nung"));
  TH1F* hNBcalClusters_nung           = static_cast<TH1F*>(fin->Get("hNBcalClusters_nung"));
  TH1F* hNBcalClusters1ISR_nung       = static_cast<TH1F*>(fin->Get("hNBcalClusters1ISR_nung"));
  TH1F* hNBcalClustersMultiISR_nung   = static_cast<TH1F*>(fin->Get("hNBcalClustersMultiISR_nung"));

  TH1F* hPt_ep_bhabhang_isr             = static_cast<TH1F*>(fin->Get("hPt_ep_bhabhang_isr"));
  TH1F* hPt_ep_bhabhang_ol              = static_cast<TH1F*>(fin->Get("hPt_ep_bhabhang_ol"));
  TH1F* hPt_ep_bhabhang_other           = static_cast<TH1F*>(fin->Get("hPt_ep_bhabhang_other"));
  TH1F* hPt_pfo_bhabhang_isr            = static_cast<TH1F*>(fin->Get("hPt_pfo_bhabhang_isr"));
  TH1F* hPt_pfo_bhabhang_ol             = static_cast<TH1F*>(fin->Get("hPt_pfo_bhabhang_ol"));
  TH1F* hPt_pfo_bhabhang_other          = static_cast<TH1F*>(fin->Get("hPt_pfo_bhabhang_other"));
  TH1F* hE_photon_bhabhang_rest         = static_cast<TH1F*>(fin->Get("hE_photon_bhabhang_rest"));
  TH1F* hE_photon_bhabhang_ol           = static_cast<TH1F*>(fin->Get("hE_photon_bhabhang_ol"));
  TH1F* hE_photon_bhabhang_electron     = static_cast<TH1F*>(fin->Get("hE_photon_bhabhang_electron"));
  TH1F* hE_V0_bhabhang_rest             = static_cast<TH1F*>(fin->Get("hE_V0_bhabhang_rest"));
  TH1F* hE_V0_bhabhang_ol               = static_cast<TH1F*>(fin->Get("hE_V0_bhabhang_ol"));
  TH1F* hE_neutron_bhabhang_rest        = static_cast<TH1F*>(fin->Get("hE_neutron_bhabhang_rest"));
  TH1F* hE_neutron_bhabhang_ol          = static_cast<TH1F*>(fin->Get("hE_neutron_bhabhang_ol"));
  TH1F* hE_electron_bhabhang_rest       = static_cast<TH1F*>(fin->Get("hE_electron_bhabhang_rest"));
  TH1F* hE_electron_bhabhang_ol         = static_cast<TH1F*>(fin->Get("hE_electron_bhabhang_ol"));
  TH1F* hE_muon_bhabhang_rest           = static_cast<TH1F*>(fin->Get("hE_muon_bhabhang_rest"));
  TH1F* hE_muon_bhabhang_ol             = static_cast<TH1F*>(fin->Get("hE_muon_bhabhang_ol"));
  TH1F* hE_pion_bhabhang_rest           = static_cast<TH1F*>(fin->Get("hE_pion_bhabhang_rest"));
  TH1F* hE_pion_bhabhang_ol             = static_cast<TH1F*>(fin->Get("hE_pion_bhabhang_ol"));
  TH1F* hEvis_pfo_bhabhang              = static_cast<TH1F*>(fin->Get("hEvis_pfo_bhabhang"));
  TH1F* hEvis_pfo_wo_pi_n_bhabhang      = static_cast<TH1F*>(fin->Get("hEvis_pfo_wo_pi_n_bhabhang"));
  TH1F* hNBcalClusters_bhabhang         = static_cast<TH1F*>(fin->Get("hNBcalClusters_bhabhang"));
  TH1F* hNBcalClusters1ISR_bhabhang     = static_cast<TH1F*>(fin->Get("hNBcalClusters1ISR_bhabhang"));
  TH1F* hNBcalClustersMultiISR_bhabhang = static_cast<TH1F*>(fin->Get("hNBcalClustersMultiISR_bhabhang"));




  hPt_ep_nung_isr->SetFillColor(kAzure+6);
  hPt_ep_nung_ol->SetFillColor(kYellow+1);
  hPt_ep_nung_other->SetFillColor(kGreen+3);
  hPt_pfo_nung_isr->SetFillColor(kAzure+6);
  hPt_pfo_nung_ol->SetFillColor(kYellow+1);
  hPt_pfo_nung_other->SetFillColor(kGreen+3);
  hE_photon_nung_rest->SetFillColor(kGreen+3);
  hE_photon_nung_ol->SetFillColor(kYellow+1);
  hE_V0_nung_rest->SetFillColor(kGreen+3);
  hE_V0_nung_ol->SetFillColor(kYellow+1);
  hE_neutron_nung_rest->SetFillColor(kGreen+3);
  hE_neutron_nung_ol->SetFillColor(kYellow+1);
  hE_electron_nung_rest->SetFillColor(kGreen+3);
  hE_electron_nung_ol->SetFillColor(kYellow+1);
  hE_muon_nung_rest->SetFillColor(kGreen+3);
  hE_muon_nung_ol->SetFillColor(kYellow+1);
  hE_pion_nung_rest->SetFillColor(kGreen+3);
  hE_pion_nung_ol->SetFillColor(kYellow+1);
  hEvis_pfo_nung->SetFillColor(kGreen+3);
  hEvis_pfo_wo_pi_n_nung->SetFillColor(kGreen+3);
  hNBcalClusters1ISR_nung->SetFillColor(kYellow+1);
  hNBcalClustersMultiISR_nung->SetFillColor(kGreen+3);

  hPt_ep_bhabhang_isr->SetFillColor(kOrange+4);
  hPt_ep_bhabhang_ol->SetFillColor(kMagenta+1);
  hPt_ep_bhabhang_other->SetFillColor(kOrange+6);
  hPt_pfo_bhabhang_isr->SetFillColor(kOrange+4);
  hPt_pfo_bhabhang_ol->SetFillColor(kMagenta+1);
  hPt_pfo_bhabhang_other->SetFillColor(kOrange+6);
  hE_photon_bhabhang_rest->SetFillColor(kOrange+6);
  hE_photon_bhabhang_electron->SetFillColor(kOrange+4);
  hE_photon_bhabhang_ol->SetFillColor(kMagenta+1);
  hE_V0_bhabhang_rest->SetFillColor(kOrange+6);
  hE_V0_bhabhang_ol->SetFillColor(kMagenta+1);
  hE_neutron_bhabhang_rest->SetFillColor(kOrange+6);
  hE_neutron_bhabhang_ol->SetFillColor(kMagenta+1);
  hE_electron_bhabhang_rest->SetFillColor(kOrange+6);
  hE_electron_bhabhang_ol->SetFillColor(kMagenta+1);
  hE_muon_bhabhang_rest->SetFillColor(kOrange+6);
  hE_muon_bhabhang_ol->SetFillColor(kMagenta+1);
  hE_pion_bhabhang_rest->SetFillColor(kOrange+6);
  hE_pion_bhabhang_ol->SetFillColor(kMagenta+1);
  hEvis_pfo_bhabhang->SetFillColor(kOrange+6);
  hEvis_pfo_wo_pi_n_bhabhang->SetFillColor(kOrange+6);
  hNBcalClusters_bhabhang->SetFillColor(kOrange+6);



  TCanvas* c1 = new TCanvas("c1","",600,400);
  gPad->SetLogy();
  THStack* hPt_e_all = new THStack("hPt_e_all",";P_{T} [GeV];");
  hPt_e_all->SetMaximum(1e10);
  hPt_e_all->SetMinimum(1);
  hPt_e_all->Add(hPt_ep_nung_other);
  hPt_e_all->Add(hPt_ep_nung_ol);
  hPt_e_all->Add(hPt_ep_nung_isr);
  hPt_e_all->Add(hPt_ep_bhabhang_ol);
  hPt_e_all->Add(hPt_ep_bhabhang_isr);
  hPt_e_all->Add(hPt_ep_bhabhang_other);
  hPt_e_all->Draw();
  TLegend* leg_c1_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c1_head->SetTextSize(0.05);
  leg_c1_head->SetTextFont(42);
  leg_c1_head->SetHeader("Transverse momenta of electrons");
  leg_c1_head->SetFillStyle(0);
  leg_c1_head->Draw();
  TLegend* leg_c1 = new TLegend(0.25,0.55,0.45,0.85);
  leg_c1->SetTextSize(0.05);
  leg_c1->SetTextFont(42);
  leg_c1->AddEntry(hPt_ep_nung_isr,  "#nu#nu+N#gamma: photons","f");
  leg_c1->AddEntry(hPt_ep_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c1->AddEntry(hPt_ep_nung_other,"#nu#nu+N#gamma: other"  ,"f");
  leg_c1->Draw();
  TLegend* leg_c1_2 = new TLegend(0.65,0.55,0.85,0.85);
  leg_c1_2->SetTextSize(0.05);
  leg_c1_2->SetTextFont(42);
  leg_c1_2->AddEntry(hPt_ep_bhabhang_other,"e^{+}e^{-}+N#gamma: other"  ,"f");
  leg_c1_2->AddEntry(hPt_ep_bhabhang_isr,  "e^{+}e^{-}+N#gamma: photons","f");
  leg_c1_2->AddEntry(hPt_ep_bhabhang_ol,   "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c1_2->Draw();

  TCanvas* c2 = new TCanvas("c2","",600,400);
  gPad->SetLogy();
  THStack* hPt_pfo_all = new THStack("hPt_pfo_all",";P_{T} [GeV];");
  hPt_pfo_all->SetMaximum(1e10);
  hPt_pfo_all->SetMinimum(1);
  hPt_pfo_all->Add(hPt_pfo_nung_other);
  hPt_pfo_all->Add(hPt_pfo_nung_ol);
  hPt_pfo_all->Add(hPt_pfo_nung_isr);
  hPt_pfo_all->Add(hPt_pfo_bhabhang_ol);
  hPt_pfo_all->Add(hPt_pfo_bhabhang_isr);
  hPt_pfo_all->Add(hPt_pfo_bhabhang_other);
  hPt_pfo_all->Draw();
  TLegend* leg_c2_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c2_head->SetTextSize(0.05);
  leg_c2_head->SetTextFont(42);
  leg_c2_head->SetHeader("Transverse momenta of charged PFOs");
  leg_c2_head->SetFillStyle(0);
  leg_c2_head->Draw();
  TLegend* leg_c2 = new TLegend(0.25,0.55,0.45,0.85);
  leg_c2->SetTextSize(0.05);
  leg_c2->SetTextFont(42);
  leg_c2->AddEntry(hPt_pfo_nung_isr,  "#nu#nu+N#gamma: photons","f");
  leg_c2->AddEntry(hPt_pfo_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c2->AddEntry(hPt_pfo_nung_other,"#nu#nu+N#gamma: other"  ,"f");
  leg_c2->Draw();
  TLegend* leg_c2_2 = new TLegend(0.65,0.55,0.85,0.85);
  leg_c2_2->SetTextSize(0.05);
  leg_c2_2->SetTextFont(42);
  leg_c2_2->AddEntry(hPt_pfo_bhabhang_other,"e^{+}e^{-}+N#gamma: other"  ,"f");
  leg_c2_2->AddEntry(hPt_pfo_bhabhang_isr,  "e^{+}e^{-}+N#gamma: photons","f");
  leg_c2_2->AddEntry(hPt_pfo_bhabhang_ol,   "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c2_2->Draw();

  TCanvas* c3 = new TCanvas("c3","",600,400);
  gPad->SetLogy();
  THStack* hE_photon_all = new THStack("hE_photon_all",";E [GeV];");
  hE_photon_all->SetMaximum(1e8);
  hE_photon_all->SetMinimum(1);
  hE_photon_all->Add(hE_photon_nung_ol);
  hE_photon_all->Add(hE_photon_nung_rest);
  hE_photon_all->Add(hE_photon_bhabhang_ol);
  hE_photon_all->Add(hE_photon_bhabhang_electron);
  hE_photon_all->Add(hE_photon_bhabhang_rest);
  hE_photon_all->Draw();
  TLegend* leg_c3_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c3_head->SetTextSize(0.05);
  leg_c3_head->SetTextFont(42);
  leg_c3_head->SetHeader("Reconstructed photons (non-ISR)");
  leg_c3_head->SetFillStyle(0);
  leg_c3_head->Draw();
  TLegend* leg_c3 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c3->SetTextSize(0.05);
  leg_c3->SetTextFont(42);
  leg_c3->AddEntry(hE_photon_nung_rest, "#nu#nu+N#gamma: rest"  ,"f");
  leg_c3->AddEntry(hE_photon_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c3->Draw();
  TLegend* leg_c3_2 = new TLegend(0.65,0.55,0.85,0.85);
  leg_c3_2->SetTextSize(0.05);
  leg_c3_2->SetTextFont(42);
  leg_c3_2->AddEntry(hE_photon_bhabhang_rest,     "e^{+}e^{-}+N#gamma: rest"  ,"f");
  leg_c3_2->AddEntry(hE_photon_bhabhang_electron, "e^{+}e^{-}+N#gamma: electron","f");
  leg_c3_2->AddEntry(hE_photon_bhabhang_ol,       "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c3_2->Draw();

  TCanvas* c4 = new TCanvas("c4","",600,400);
  gPad->SetLogy();
  THStack* hE_V0_all = new THStack("hE_V0_all",";E [GeV];");
  hE_V0_all->SetMaximum(1e8);
  hE_V0_all->SetMinimum(1);
  hE_V0_all->Add(hE_V0_nung_ol);
  hE_V0_all->Add(hE_V0_nung_rest);
  hE_V0_all->Add(hE_V0_bhabhang_ol);
  hE_V0_all->Add(hE_V0_bhabhang_rest);
  hE_V0_all->Draw();
  TLegend* leg_c4_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c4_head->SetTextSize(0.05);
  leg_c4_head->SetTextFont(42);
  leg_c4_head->SetHeader("Reconstructed V0 objects");
  leg_c4_head->SetFillStyle(0);
  leg_c4_head->Draw();
  TLegend* leg_c4 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c4->SetTextSize(0.05);
  leg_c4->SetTextFont(42);
  leg_c4->AddEntry(hE_V0_nung_rest, "#nu#nu+N#gamma: rest"  ,"f");
  leg_c4->AddEntry(hE_V0_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c4->Draw();
  TLegend* leg_c4_2 = new TLegend(0.65,0.65,0.85,0.85);
  leg_c4_2->SetTextSize(0.05);
  leg_c4_2->SetTextFont(42);
  leg_c4_2->AddEntry(hE_V0_bhabhang_rest,     "e^{+}e^{-}+N#gamma: rest"  ,"f");
  leg_c4_2->AddEntry(hE_V0_bhabhang_ol,       "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c4_2->Draw();

  TCanvas* c5 = new TCanvas("c5","",600,400);
  gPad->SetLogy();
  THStack* hE_neutron_all = new THStack("hE_neutron_all",";E [GeV];");
  hE_neutron_all->SetMaximum(1e8);
  hE_neutron_all->SetMinimum(1);
  hE_neutron_all->Add(hE_neutron_nung_ol);
  hE_neutron_all->Add(hE_neutron_nung_rest);
  hE_neutron_all->Add(hE_neutron_bhabhang_ol);
  hE_neutron_all->Add(hE_neutron_bhabhang_rest);
  hE_neutron_all->Draw();
  TLegend* leg_c5_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c5_head->SetTextSize(0.05);
  leg_c5_head->SetTextFont(42);
  leg_c5_head->SetHeader("Reconstructed neutrons");
  leg_c5_head->SetFillStyle(0);
  leg_c5_head->Draw();
  TLegend* leg_c5 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c5->SetTextSize(0.05);
  leg_c5->SetTextFont(42);
  leg_c5->AddEntry(hE_neutron_nung_rest, "#nu#nu+N#gamma: rest"  ,"f");
  leg_c5->AddEntry(hE_neutron_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c5->Draw();
  TLegend* leg_c5_2 = new TLegend(0.65,0.65,0.85,0.85);
  leg_c5_2->SetTextSize(0.05);
  leg_c5_2->SetTextFont(42);
  leg_c5_2->AddEntry(hE_neutron_bhabhang_rest,     "e^{+}e^{-}+N#gamma: rest"  ,"f");
  leg_c5_2->AddEntry(hE_neutron_bhabhang_ol,       "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c5_2->Draw();

  TCanvas* c6 = new TCanvas("c6","",600,400);
  gPad->SetLogy();
  THStack* hE_electron_all = new THStack("hE_electron_all",";E [GeV];");
  hE_electron_all->SetMaximum(1e8);
  hE_electron_all->SetMinimum(1);
  hE_electron_all->Add(hE_electron_nung_ol);
  hE_electron_all->Add(hE_electron_nung_rest);
  hE_electron_all->Add(hE_electron_bhabhang_ol);
  hE_electron_all->Add(hE_electron_bhabhang_rest);
  hE_electron_all->Draw();
  TLegend* leg_c6_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c6_head->SetTextSize(0.05);
  leg_c6_head->SetTextFont(42);
  leg_c6_head->SetHeader("Reconstructed electrons");
  leg_c6_head->SetFillStyle(0);
  leg_c6_head->Draw();
  TLegend* leg_c6 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c6->SetTextSize(0.05);
  leg_c6->SetTextFont(42);
  leg_c6->AddEntry(hE_electron_nung_rest, "#nu#nu+N#gamma: rest"  ,"f");
  leg_c6->AddEntry(hE_electron_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c6->Draw();
  TLegend* leg_c6_2 = new TLegend(0.65,0.65,0.85,0.85);
  leg_c6_2->SetTextSize(0.05);
  leg_c6_2->SetTextFont(42);
  leg_c6_2->AddEntry(hE_electron_bhabhang_rest,     "e^{+}e^{-}+N#gamma: rest"  ,"f");
  leg_c6_2->AddEntry(hE_electron_bhabhang_ol,       "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c6_2->Draw();

  TCanvas* c7 = new TCanvas("c7","",600,400);
  gPad->SetLogy();
  THStack* hE_muon_all = new THStack("hE_muon_all",";E [GeV];");
  hE_muon_all->SetMaximum(1e8);
  hE_muon_all->SetMinimum(1);
  hE_muon_all->Add(hE_muon_nung_ol);
  hE_muon_all->Add(hE_muon_nung_rest);
  hE_muon_all->Add(hE_muon_bhabhang_ol);
  hE_muon_all->Add(hE_muon_bhabhang_rest);
  hE_muon_all->Draw();
  TLegend* leg_c7_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c7_head->SetTextSize(0.05);
  leg_c7_head->SetTextFont(42);
  leg_c7_head->SetHeader("Reconstructed muons");
  leg_c7_head->SetFillStyle(0);
  leg_c7_head->Draw();
  TLegend* leg_c7 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c7->SetTextSize(0.05);
  leg_c7->SetTextFont(42);
  leg_c7->AddEntry(hE_muon_nung_rest, "#nu#nu+N#gamma: rest"  ,"f");
  leg_c7->AddEntry(hE_muon_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c7->Draw();
  TLegend* leg_c7_2 = new TLegend(0.65,0.65,0.85,0.85);
  leg_c7_2->SetTextSize(0.05);
  leg_c7_2->SetTextFont(42);
  leg_c7_2->AddEntry(hE_muon_bhabhang_rest,     "e^{+}e^{-}+N#gamma: rest"  ,"f");
  leg_c7_2->AddEntry(hE_muon_bhabhang_ol,       "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c7_2->Draw();

  TCanvas* c8 = new TCanvas("c8","",600,400);
  gPad->SetLogy();
  THStack* hE_pion_all = new THStack("hE_pion_all",";E [GeV];");
  hE_pion_all->SetMaximum(1e8);
  hE_pion_all->SetMinimum(1);
  hE_pion_all->Add(hE_pion_nung_ol);
  hE_pion_all->Add(hE_pion_nung_rest);
  hE_pion_all->Add(hE_pion_bhabhang_ol);
  hE_pion_all->Add(hE_pion_bhabhang_rest);
  hE_pion_all->Draw();
  TLegend* leg_c8_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c8_head->SetTextSize(0.05);
  leg_c8_head->SetTextFont(42);
  leg_c8_head->SetHeader("Reconstructed pions");
  leg_c8_head->SetFillStyle(0);
  leg_c8_head->Draw();
  TLegend* leg_c8 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c8->SetTextSize(0.05);
  leg_c8->SetTextFont(42);
  leg_c8->AddEntry(hE_pion_nung_rest, "#nu#nu+N#gamma: rest"  ,"f");
  leg_c8->AddEntry(hE_pion_nung_ol,   "#nu#nu+N#gamma: overlay","f");
  leg_c8->Draw();
  TLegend* leg_c8_2 = new TLegend(0.65,0.65,0.85,0.85);
  leg_c8_2->SetTextSize(0.05);
  leg_c8_2->SetTextFont(42);
  leg_c8_2->AddEntry(hE_pion_bhabhang_rest,     "e^{+}e^{-}+N#gamma: rest"  ,"f");
  leg_c8_2->AddEntry(hE_pion_bhabhang_ol,       "e^{+}e^{-}+N#gamma: overlay","f");
  leg_c8_2->Draw();

  TCanvas* c9 = new TCanvas("c9","",600,400);
  gPad->SetLogy();
  THStack* hEvis_all = new THStack("hEvis_all",";Evis [GeV];");
  hEvis_all->SetMaximum(1e8);
  hEvis_all->SetMinimum(1);
  hEvis_all->Add(hEvis_pfo_nung);
  hEvis_all->Add(hEvis_pfo_bhabhang);
  hEvis_all->Draw();
  TLegend* leg_c9_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c9_head->SetTextSize(0.05);
  leg_c9_head->SetTextFont(42);
  leg_c9_head->SetHeader("Visible energy: PFOs > 5GeV, all types");
  leg_c9_head->SetFillStyle(0);
  leg_c9_head->Draw();
  TLegend* leg_c9 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c9->SetTextSize(0.04);
  leg_c9->SetTextFont(42);
  leg_c9->AddEntry(hEvis_pfo_bhabhang, "e^{+}e^{-}+N#gamma" ,"f");
  leg_c9->AddEntry(hEvis_pfo_nung,     "#nu#nu+N#gamma"     ,"f");
  leg_c9->Draw();

  TCanvas* c10 = new TCanvas("c10","",600,400);
  gPad->SetLogy();
  THStack* hEvis_wo_pi_n_all = new THStack("hEvis_wo_pi_n_all",";Evis [GeV];");
  hEvis_wo_pi_n_all->SetMaximum(1e8);
  hEvis_wo_pi_n_all->SetMinimum(1);
  hEvis_wo_pi_n_all->Add(hEvis_pfo_wo_pi_n_nung);
  hEvis_wo_pi_n_all->Add(hEvis_pfo_wo_pi_n_bhabhang);
  hEvis_wo_pi_n_all->Draw();
  TLegend* leg_c10_head = new TLegend(0.25,0.85,0.9,0.9);
  leg_c10_head->SetTextSize(0.05);
  leg_c10_head->SetTextFont(42);
  leg_c10_head->SetHeader("Visible energy: PFOs > 5GeV, w/o #pi,n");
  leg_c10_head->SetFillStyle(0);
  leg_c10_head->Draw();
  TLegend* leg_c10 = new TLegend(0.25,0.65,0.45,0.85);
  leg_c10->SetTextSize(0.04);
  leg_c10->SetTextFont(42);
  leg_c10->AddEntry(hEvis_pfo_wo_pi_n_bhabhang, "e^{+}e^{-}+N#gamma" ,"f");
  leg_c10->AddEntry(hEvis_pfo_wo_pi_n_nung,     "#nu#nu+N#gamma"     ,"f");
  leg_c10->Draw();

  TCanvas* c11 = new TCanvas("c11","",600,400);
  gPad->SetLogy();
  /* 
   * Note these histograms were not stacked in Moritz thesis,
   */
#if 1 // stacked version. Note that MultiISR means # of ISR to be more than 1.
  THStack* hNBcalClusters_all = new THStack("hNBcalClusters_all",";# of BCal clusters;");
  hNBcalClusters_all->SetMaximum(1e10);
  hNBcalClusters_all->SetMinimum(1);
  hNBcalClusters_all->Add(hNBcalClusters1ISR_nung);
  hNBcalClusters_all->Add(hNBcalClustersMultiISR_nung);
  hNBcalClusters_all->Add(hNBcalClusters_bhabhang);
  hNBcalClusters_all->Draw(); 
  TLegend* leg_c11_head = new TLegend(0.5,0.85,0.9,0.9);
  leg_c11_head->SetTextSize(0.05);
  leg_c11_head->SetTextFont(42);
  leg_c11_head->SetHeader("Number of BeamCal clusters");
  leg_c11_head->SetFillStyle(0);
  leg_c11_head->Draw();
  TLegend* leg_c11 = new TLegend(0.65,0.55,0.9,0.85);
  leg_c11->SetTextSize(0.04);
  leg_c11->SetTextFont(42);
  leg_c11->AddEntry(hNBcalClusters_bhabhang,     "e^{+}e^{-}+N#gamma (N>0)" ,"f");
  leg_c11->AddEntry(hNBcalClustersMultiISR_nung, "#nu#nu+N#gamma (N>1)"     ,"f");
  leg_c11->AddEntry(hNBcalClusters1ISR_nung,     "#nu#nu+1#gamma"           ,"f");
  leg_c11->Draw();
#else // Moritz's version
  hNBcalClustersMultiISR->SetMinimum(1);
  hNBcalClustersMultiISR_nung->Draw();
  hNBcalClusters1ISR_nung->Draw("same");
  hNBcalClusters_bhabhang->Draw("same");
  TLegend* leg_c11_head = new TLegend(0.65,0.85,0.9,0.9,"Number of BeamCal clusters");
  leg_c11_head->SetFillStyle(0);
  leg_c11_head->Draw();
  TLegend* leg_c11 = new TLegend(0.65,0.55,0.9,0.85);
  leg_c11->AddEntry(hNBcalClusters_bhabhang,     "e^{+}e^{-}+N#gamma" ,"f");
  leg_c11->AddEntry(hNBcalClustersMultiISR_nung, "#nu#nu+N#gamma"     ,"f");
  leg_c11->AddEntry(hNBcalClusters1ISR_nung,     "#nu#nu+1#gamma"     ,"f");
  leg_c11->Draw();
#endif

  TCanvas* c12 = new TCanvas("c12","",600,400);
  gPad->SetLogy();
  hE_photon_nung->Draw();

  TCanvas* c13 = new TCanvas("c13","",600,400);
  gPad->SetLogy();
  hNrecNgen_photon_nung->DrawNormalized();

  TCanvas* c14 = new TCanvas("c14","",600,400);
  gNrecNgenEmc_photon_nung->GetXaxis()->SetRangeUser(0.,250.);
  gNrecNgenEmc_photon_nung->GetYaxis()->SetRangeUser(0.99,1.03);
  gNrecNgenEmc_photon_nung->Draw("ap");

  TCanvas* c15 = new TCanvas("c15","",600,400);
  gNrecNgenCostheta_photon_nung->Draw("ap");
  gNrecNgenCostheta_photon_nung->GetXaxis()->SetRangeUser(0.,1.);
  gNrecNgenCostheta_photon_nung->GetYaxis()->SetRangeUser(0.99,1.15);
}
